In [3]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_json("D:/credit score assign/dataset/user-wallet-transactions.json")

In [5]:
df.columns

Index(['_id', 'userWallet', 'network', 'protocol', 'txHash', 'logId',
       'timestamp', 'blockNumber', 'action', 'actionData', '__v', 'createdAt',
       'updatedAt'],
      dtype='object')

In [6]:
df.head()

,_id,userWallet,network,protocol,txHash,logId,timestamp,blockNumber,action,actionData,__v,createdAt,updatedAt
0,{'$oid': '681d38fed63812d4655f571a'},0x00000000001accfa9cef68cf5371a23025b6d4b6,polygon,aave_v2,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,2021-08-17 05:29:26,1629178166,deposit,"{'type': 'Deposit', 'amount': '2000000000', 'a...",0,{'$date': '2025-05-08T23:06:39.465Z'},{'$date': '2025-05-08T23:06:39.465Z'}
1,{'$oid': '681aa70dd6df53021cc6f3c0'},0x000000000051d07a4fb3bd10121a343d85818da6,polygon,aave_v2,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,2021-05-20 15:36:53,1621525013,deposit,"{'type': 'Deposit', 'amount': '145000000000000...",0,{'$date': '2025-05-07T00:19:26.159Z'},{'$date': '2025-05-07T00:19:26.159Z'}
2,{'$oid': '681d04c2d63812d4654c733e'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,2021-07-24 09:28:33,1627118913,deposit,"{'type': 'Deposit', 'amount': '100000000000000...",0,{'$date': '2025-05-08T19:23:47.877Z'},{'$date': '2025-05-08T19:23:47.877Z'}
3,{'$oid': '681d133bd63812d46551b6ef'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,2021-07-31 23:15:18,1627773318,deposit,"{'type': 'Deposit', 'amount': '400000000000000...",0,{'$date': '2025-05-08T20:25:33.141Z'},{'$date': '2025-05-08T20:25:33.141Z'}
4,{'$oid': '681899e4ba49fc91cf2f4454'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,2021-04-19 15:25:07,1618845907,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '501548...",0,{'$date': '2025-05-05T10:58:45.934Z'},{'$date': '2025-05-05T10:58:45.934Z'}

In [7]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [8]:
df.head()

,_id,userWallet,network,protocol,txHash,logId,timestamp,blockNumber,action,actionData,__v,createdAt,updatedAt
0,{'$oid': '681d38fed63812d4655f571a'},0x00000000001accfa9cef68cf5371a23025b6d4b6,polygon,aave_v2,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,2021-08-17 05:29:26,1629178166,deposit,"{'type': 'Deposit', 'amount': '2000000000', 'a...",0,{'$date': '2025-05-08T23:06:39.465Z'},{'$date': '2025-05-08T23:06:39.465Z'}
1,{'$oid': '681aa70dd6df53021cc6f3c0'},0x000000000051d07a4fb3bd10121a343d85818da6,polygon,aave_v2,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,2021-05-20 15:36:53,1621525013,deposit,"{'type': 'Deposit', 'amount': '145000000000000...",0,{'$date': '2025-05-07T00:19:26.159Z'},{'$date': '2025-05-07T00:19:26.159Z'}
2,{'$oid': '681d04c2d63812d4654c733e'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,2021-07-24 09:28:33,1627118913,deposit,"{'type': 'Deposit', 'amount': '100000000000000...",0,{'$date': '2025-05-08T19:23:47.877Z'},{'$date': '2025-05-08T19:23:47.877Z'}
3,{'$oid': '681d133bd63812d46551b6ef'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,2021-07-31 23:15:18,1627773318,deposit,"{'type': 'Deposit', 'amount': '400000000000000...",0,{'$date': '2025-05-08T20:25:33.141Z'},{'$date': '2025-05-08T20:25:33.141Z'}
4,{'$oid': '681899e4ba49fc91cf2f4454'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,2021-04-19 15:25:07,1618845907,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '501548...",0,{'$date': '2025-05-05T10:58:45.934Z'},{'$date': '2025-05-05T10:58:45.934Z'}

In [9]:
def get_amount(x):
    return x.get("amount")

In [10]:
df["amount"]=df["actionData"].apply(get_amount)

In [11]:
df["action"].unique()

array(['deposit', 'redeemunderlying', 'borrow', 'repay',
       'liquidationcall'], dtype=object)

In [12]:
group=df.groupby("userWallet")

In [13]:
def generate_features(df):
    grouped = df.groupby('userWallet')

    features = pd.DataFrame()
    features['num_transactions'] = grouped.size()
    features['num_deposits'] = grouped.apply(lambda x: (x['action'] == 'deposit').sum())
    features['num_borrows'] = grouped.apply(lambda x: (x['action'] == 'borrow').sum())
    features['num_repays'] = grouped.apply(lambda x: (x['action'] == 'repay').sum())
    features['num_liquidations'] = grouped.apply(lambda x: (x['action'] == 'liquidationcall').sum())

    features['total_borrowed'] = grouped.apply(lambda x: x[x['action'] == 'borrow']['amount'].sum())
    features['total_repaid'] = grouped.apply(lambda x: x[x['action'] == 'repay']['amount'].sum())
    features['total_deposited'] = grouped.apply(lambda x: x[x['action'] == 'deposit']['amount'].sum())
    features['total_repaid'] = features['total_repaid'].astype(float)
    features['total_borrowed'] = features['total_borrowed'].astype(float)
    features['total_deposited'] = features['total_deposited'].astype(float)

    features['repay_ratio'] = features['total_repaid'] / features['total_borrowed'].replace(0, 1)
    features['borrow_to_deposit_ratio'] = features['total_borrowed'] / features['total_deposited'].replace(0, 1)

    # Active time span
    features['first_txn'] = grouped['timestamp'].min()
    features['last_txn'] = grouped['timestamp'].max()
    features['active_days'] = (features['last_txn'] - features['first_txn']).dt.days + 1

    return features.reset_index()

In [14]:
feature_data=generate_features(df)

In [15]:
import numpy as np

In [16]:
feature_data = feature_data.replace([np.inf, -np.inf], np.nan)

In [17]:
feature_data=feature_data.fillna(0)

In [18]:
feature_data

,userWallet,num_transactions,num_deposits,num_borrows,num_repays,num_liquidations,total_borrowed,total_repaid,total_deposited,repay_ratio,borrow_to_deposit_ratio,first_txn,last_txn,active_days
0,0x00000000001accfa9cef68cf5371a23025b6d4b6,1,1,0,0,0,0.000000e+00,0.000000e+00,2.000000e+09,0.000000e+00,0.000000e+00,2021-08-17 05:29:26,2021-08-17 05:29:26,1
1,0x000000000051d07a4fb3bd10121a343d85818da6,1,1,0,0,0,0.000000e+00,0.000000e+00,1.450000e+20,0.000000e+00,0.000000e+00,2021-05-20 15:36:53,2021-05-20 15:36:53,1
2,0x000000000096026fb41fc39f9875d164bd82e2dc,2,2,0,0,0,0.000000e+00,0.000000e+00,1.000000e+31,0.000000e+00,0.000000e+00,2021-07-24 09:28:33,2021-07-31 23:15:18,8
3,0x0000000000e189dd664b9ab08a33c4839953852c,17,0,0,0,0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2021-04-19 15:23:17,2021-08-26 23:15:16,130
4,0x0000000002032370b971dabd36d72f3e5a7bf1ee,399,250,15,4,0,7.000000e+307,1.002107e+40,0.000000e+00,1.431581e-268,0.000000e+00,2021-04-21 21:28:30,2021-09-01 18:15:24,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492,0x06185db89f5c8ef5e5a0abc95c5cb69b54c33f30,1,1,0,0,0,0.000000e+00,0.000000e+00,9.800000e+01,0.000000e+00,0.000000e+00,2021-07-12 22:31:43,2021-07-12 22:31:43,1
3493,0x06189341e523a52ae10c4bd4a7774371fac1b249,7,4,1,0,0,1.250000e+18,0.000000e+00,6.064408e+63,0.000000e+00,2.061207e-46,2021-05-30 07:22:19,2021-05-30 14:02:49,1
3494,0x0618c450370822c5cb25ec143a3008230d8e2c12,5,1,0,0,0,0.000000e+00,0.000000e+00,1.410546e+19,0.000000e+00,0.000000e+00,2021-05-20 03:52:58,2021-05-20 04:08:15,1
3495,0x0618e615c8c9b5efc8c8eadc68be7182bdc455e2,22,13,2,2,0,2.000000e+18,2.000000e+14,2.263515e+251,1.000000e-04,8.835814e-234,2021-06-10 22:09:52,2021-07-11 23:44:47,32
3496,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,183,53,48,36,0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2021-04-16 19:02:01,2021-06-15 08:26:17,60

In [19]:
def score(df):
    score=df["repay_ratio"]*500+df["borrow_to_deposit_ratio"]*200-df["num_liquidations"]*50+df["total_deposited"]*10
    return int(round(min(max(score, 0), 1000), -2))

In [20]:

cols_to_fix = [
    'repay_ratio',
    'borrow_to_deposit_ratio',
    'total_deposited',
    'num_liquidations'
]

In [21]:
feature_data[cols_to_fix] = feature_data[cols_to_fix].fillna(0)

In [22]:
feature_data["Score"]=feature_data.apply(score,axis=1)

In [23]:
feature_data.head()

,userWallet,num_transactions,num_deposits,num_borrows,num_repays,num_liquidations,total_borrowed,total_repaid,total_deposited,repay_ratio,borrow_to_deposit_ratio,first_txn,last_txn,active_days,Score
0,0x00000000001accfa9cef68cf5371a23025b6d4b6,1,1,0,0,0,0.000000e+00,0.000000e+00,2.000000e+09,0.000000e+00,0.0,2021-08-17 05:29:26,2021-08-17 05:29:26,1,1000
1,0x000000000051d07a4fb3bd10121a343d85818da6,1,1,0,0,0,0.000000e+00,0.000000e+00,1.450000e+20,0.000000e+00,0.0,2021-05-20 15:36:53,2021-05-20 15:36:53,1,1000
2,0x000000000096026fb41fc39f9875d164bd82e2dc,2,2,0,0,0,0.000000e+00,0.000000e+00,1.000000e+31,0.000000e+00,0.0,2021-07-24 09:28:33,2021-07-31 23:15:18,8,1000
3,0x0000000000e189dd664b9ab08a33c4839953852c,17,0,0,0,0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,2021-04-19 15:23:17,2021-08-26 23:15:16,130,0
4,0x0000000002032370b971dabd36d72f3e5a7bf1ee,399,250,15,4,0,7.000000e+307,1.002107e+40,0.000000e+00,1.431581e-268,0.0,2021-04-21 21:28:30,2021-09-01 18:15:24,133,0

In [24]:
feature_data["Score"].unique()

array([1000,    0,  500,  100,  300,  900], dtype=int64)

In [25]:
feature_data['total_borrowed'] = feature_data['total_borrowed'].clip(upper=1e6)
feature_data['total_repaid'] = feature_data['total_repaid'].clip(upper=1e6)
feature_data['total_deposited'] = feature_data['total_deposited'].clip(upper=1e6)
feature_data['repay_ratio'] = feature_data['repay_ratio'].clip(upper=1)  # Should never be >1
feature_data['borrow_to_deposit_ratio'] = feature_data['borrow_to_deposit_ratio'].clip(upper=5)  # Keep it san

In [26]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [27]:
X=feature_data.drop(columns=['userWallet', 'first_txn', 'last_txn', 'Score'])
y=feature_data["Score"]

In [28]:
X.replace([np.inf, -np.inf], np.nan, inplace=True)
X.fillna(0,inplace=True)

In [29]:
print("Any infs left?", np.isinf(X.values).sum())

Any infs left? 0

In [30]:
print("Max values in each column:")
print(X.max())

print("\nMin values in each column:")
print(X.min())

Max values in each column:
num_transactions             14265.0
num_deposits                   511.0
num_borrows                    200.0
num_repays                     291.0
num_liquidations                26.0
total_borrowed             1000000.0
total_repaid               1000000.0
total_deposited            1000000.0
repay_ratio                      1.0
borrow_to_deposit_ratio          5.0
active_days                    154.0
dtype: float64

Min values in each column:
num_transactions           1.0
num_deposits               0.0
num_borrows                0.0
num_repays                 0.0
num_liquidations           0.0
total_borrowed             0.0
total_repaid               0.0
total_deposited            0.0
repay_ratio                0.0
borrow_to_deposit_ratio    0.0
active_days                1.0
dtype: float64

In [31]:
y.isnull().sum()

0

In [32]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [33]:
randomforest=RandomForestRegressor()

In [34]:
randomforest.fit(x_train,y_train)

RandomForestRegressor()

In [35]:
from sklearn.preprocessing import MinMaxScaler

In [36]:
scaler = MinMaxScaler(feature_range=(0, 1000))

In [37]:
feature_data['predicted_score'] = randomforest.predict(X)

In [38]:
feature_data

,userWallet,num_transactions,num_deposits,num_borrows,num_repays,num_liquidations,total_borrowed,total_repaid,total_deposited,repay_ratio,borrow_to_deposit_ratio,first_txn,last_txn,active_days,Score,predicted_score
0,0x00000000001accfa9cef68cf5371a23025b6d4b6,1,1,0,0,0,0.0,0.0,1000000.0,0.000000e+00,0.000000e+00,2021-08-17 05:29:26,2021-08-17 05:29:26,1,1000,1000.0
1,0x000000000051d07a4fb3bd10121a343d85818da6,1,1,0,0,0,0.0,0.0,1000000.0,0.000000e+00,0.000000e+00,2021-05-20 15:36:53,2021-05-20 15:36:53,1,1000,1000.0
2,0x000000000096026fb41fc39f9875d164bd82e2dc,2,2,0,0,0,0.0,0.0,1000000.0,0.000000e+00,0.000000e+00,2021-07-24 09:28:33,2021-07-31 23:15:18,8,1000,1000.0
3,0x0000000000e189dd664b9ab08a33c4839953852c,17,0,0,0,0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,2021-04-19 15:23:17,2021-08-26 23:15:16,130,0,0.0
4,0x0000000002032370b971dabd36d72f3e5a7bf1ee,399,250,15,4,0,1000000.0,1000000.0,0.0,1.431581e-268,0.000000e+00,2021-04-21 21:28:30,2021-09-01 18:15:24,133,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492,0x06185db89f5c8ef5e5a0abc95c5cb69b54c33f30,1,1,0,0,0,0.0,0.0,98.0,0.000000e+00,0.000000e+00,2021-07-12 22:31:43,2021-07-12 22:31:43,1,1000,985.0
3493,0x06189341e523a52ae10c4bd4a7774371fac1b249,7,4,1,0,0,1000000.0,0.0,1000000.0,0.000000e+00,2.061207e-46,2021-05-30 07:22:19,2021-05-30 14:02:49,1,1000,1000.0
3494,0x0618c450370822c5cb25ec143a3008230d8e2c12,5,1,0,0,0,0.0,0.0,1000000.0,0.000000e+00,0.000000e+00,2021-05-20 03:52:58,2021-05-20 04:08:15,1,1000,1000.0
3495,0x0618e615c8c9b5efc8c8eadc68be7182bdc455e2,22,13,2,2,0,1000000.0,1000000.0,1000000.0,1.000000e-04,8.835814e-234,2021-06-10 22:09:52,2021-07-11 23:44:47,32,1000,1000.0
3496,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,183,53,48,36,0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,2021-04-16 19:02:01,2021-06-15 08:26:17,60,0,0.0

In [39]:
feature_data['normalized_score'] = scaler.fit_transform(feature_data[['predicted_score']])

In [40]:
feature_data

,userWallet,num_transactions,num_deposits,num_borrows,num_repays,num_liquidations,total_borrowed,total_repaid,total_deposited,repay_ratio,borrow_to_deposit_ratio,first_txn,last_txn,active_days,Score,predicted_score,normalized_score
0,0x00000000001accfa9cef68cf5371a23025b6d4b6,1,1,0,0,0,0.0,0.0,1000000.0,0.000000e+00,0.000000e+00,2021-08-17 05:29:26,2021-08-17 05:29:26,1,1000,1000.0,1000.0
1,0x000000000051d07a4fb3bd10121a343d85818da6,1,1,0,0,0,0.0,0.0,1000000.0,0.000000e+00,0.000000e+00,2021-05-20 15:36:53,2021-05-20 15:36:53,1,1000,1000.0,1000.0
2,0x000000000096026fb41fc39f9875d164bd82e2dc,2,2,0,0,0,0.0,0.0,1000000.0,0.000000e+00,0.000000e+00,2021-07-24 09:28:33,2021-07-31 23:15:18,8,1000,1000.0,1000.0
3,0x0000000000e189dd664b9ab08a33c4839953852c,17,0,0,0,0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,2021-04-19 15:23:17,2021-08-26 23:15:16,130,0,0.0,0.0
4,0x0000000002032370b971dabd36d72f3e5a7bf1ee,399,250,15,4,0,1000000.0,1000000.0,0.0,1.431581e-268,0.000000e+00,2021-04-21 21:28:30,2021-09-01 18:15:24,133,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492,0x06185db89f5c8ef5e5a0abc95c5cb69b54c33f30,1,1,0,0,0,0.0,0.0,98.0,0.000000e+00,0.000000e+00,2021-07-12 22:31:43,2021-07-12 22:31:43,1,1000,985.0,985.0
3493,0x06189341e523a52ae10c4bd4a7774371fac1b249,7,4,1,0,0,1000000.0,0.0,1000000.0,0.000000e+00,2.061207e-46,2021-05-30 07:22:19,2021-05-30 14:02:49,1,1000,1000.0,1000.0
3494,0x0618c450370822c5cb25ec143a3008230d8e2c12,5,1,0,0,0,0.0,0.0,1000000.0,0.000000e+00,0.000000e+00,2021-05-20 03:52:58,2021-05-20 04:08:15,1,1000,1000.0,1000.0
3495,0x0618e615c8c9b5efc8c8eadc68be7182bdc455e2,22,13,2,2,0,1000000.0,1000000.0,1000000.0,1.000000e-04,8.835814e-234,2021-06-10 22:09:52,2021-07-11 23:44:47,32,1000,1000.0,1000.0
3496,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,183,53,48,36,0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,2021-04-16 19:02:01,2021-06-15 08:26:17,60,0,0.0,0.0

In [41]:
final_scores = feature_data[['userWallet', 'normalized_score']]
final_scores.columns = ['wallet', 'credit_score']
final_scores = final_scores.set_index('wallet')

print(final_scores["credit_score"].unique())

[1000.    0.  985.  860.  990.  605.   62.  213.  840.  560.  995.  595.
   82.   12.  980.  895.  926.  690.  760.  975.  715.  965.]

In [42]:
import pickle

In [43]:
pickle.dump(randomforest,open("Score_assign_model.pkl","wb"))

In [44]:
pickle.dump(scaler,open("scaler_model.pkl","wb"))